spring:
  datasource:
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
  security:
    user:
      name: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    generate-ddl: true 
springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true

server:
  servlet:
    context-path: '/api/'