spring:
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: true

server:
  servlet:
    context-path: '/api/'